//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonMogendorff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateHour { get; set; }
        public string FeedbackText { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
