//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonMogendorff
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameResult
    {
        public int GameResultID { get; set; }
        public int UserID { get; set; }
        public System.DateTime GameDateTime { get; set; }
        public System.TimeSpan GameTime { get; set; }
        public int StepNumber { get; set; }
    
        public virtual GameResult GameResult1 { get; set; }
        public virtual GameResult GameResult2 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
